### ISSUE TITLE
How to make JSF recognize I am trying to edit a record from an AngularTable

### ISSUE THREAD

**Issue by ratcashdev** [stephanrauh/AngularFaces#13]
This is really just a support question, no bug or similar. Let assume we have an ngTable:
``` java
<table ng-table="tableParams" value="{{personController.list}}" class="table ng-table-responsive">
    <tbody>
		<tr ng-repeat="person in $data">
			<td data-title="'ID'">{{person.id}}</td>
			<td data-title="'Name'">{{person.firstName}} {{person.lastName}}</td>
			<td data-title="'Gender'">{{person.gender}}</td>
			<td><div class="btn-toolbar"><input type="submit" value="edit" jsf:action="#{personController.doEdit(person.id)}" class="btn btn-primary btn-sm"/> 
				<input type="submit" value="delete" jsf:action="#{personController.delete(person.id)}" class="btn btn-sm btn-danger"/></div></td>
		</tr>
	</tbody>
</table>
```

How would I tell JSF that I want to edit/delete certain rows when clicking on the buttons in the btn-toolbar? The current solution correctly tells JSF that I want to edit (and the proper edit form is rendered below the table), but JSF does not know which item is to be edited, and therefore the form stays empty.

**Comment by stephanrauh** [comment]
I'm moving the issue to version 2.2 because there are a couple of solutions, but they're not as elegant as I want them to be.
