### ISSUE TITLE
[perf] pass FacesContext to Utils if available

### ISSUE THREAD

**Issue by tandraschko** [stephanrauh/AngularFaces#23]
You always get the FC via FacesContext.getCurrentInstance()
Its just a small improvement but 10 small improvents = 1 big improvement ;)

**Comment by stephanrauh** [comment]
AngularFaces was an interesting project, but it turned out to be impossible to migrate it to Angular 2, and since the, the Java community has abandoned UI programming altogether. So I'm closing all remaining tickets and archive the project.
