### ISSUE TITLE
[perf] optimize TagAttributeUtilities

### ISSUE THREAD

**Issue by tandraschko** [stephanrauh/AngularFaces#25]
possible solutions:
1) check if there is really no API-based way
2) provide a implementation for mojarra/myfaces in own maven modules
3) cache the constructor

**Comment by stephanrauh** [comment]
AngularFaces was an interesting project, but it turned out to be impossible to migrate it to Angular 2, and since the, the Java community has abandoned UI programming altogether. So I'm closing all remaining tickets and archive the project.
