### ISSUE TITLE
[perf] check I18n bean

### ISSUE THREAD

**Issue by tandraschko** [stephanrauh/AngularFaces#26]
Currently it's ViewScoped and therefore ALL translations will be in the viewstate
if you have many translations, the viewstate will be really big...

**Comment by stephanrauh** [comment]
AngularFaces was an interesting project, but it turned out to be impossible to migrate it to Angular 2, and since the, the Java community has abandoned UI programming altogether. So I'm closing all remaining tickets and archive the project.
