### ISSUE TITLE
[perf] check caching in ELTools

### ISSUE THREAD

**Issue by tandraschko** [stephanrauh/AngularFaces#27]
its dangerous...

**Comment by stephanrauh** [comment]
AngularFaces works without caching, so we can shift this ticket to version 2.2, which is going to be a performance enhancement version :).

**Comment by stephanrauh** [comment]
AngularFaces was an interesting project, but it turned out to be impossible to migrate it to Angular 2, and since the, the Java community has abandoned UI programming altogether. So I'm closing all remaining tickets and archive the project.
