### ISSUE TITLE
Tutorial out of date?

### ISSUE THREAD

**Issue by stebiger** [stephanrauh/AngularFaces#30]
Hi,

I was trying to dig into AngularFaces but have noticed that your tutorial seems to be out of date?
Downloading the master didn't get me any "Tutorial"-Project which was listed by eclipse.
Further no folder was also included in that case.

Is my assumption wrong and can you correct me?
I'd love to dig into AngularFaces but need a well prepared start with your tutorial.

Regards,
Stefan

**Comment by stephanrauh** [comment]
The new documentation is available at https://www.angularfaces.net.

**Comment by bovino** [comment]
if you guys have interest on translating AngularFaces documentation and
samples to brazilian portuguese, please let me know

**Comment by stephanrauh** [comment]
Whow! Sim! Obrigado!

Brazil is one of the countries most interested in JSF and AngularFaces. So your translation helps many developers. Plus, it's a nice demonstration of the internationalization features of AngularFaces.

The source code of the documentation is in the AngularFaces.net subfolder of this repository.

Adeus,
Stephan

**Comment by bovino** [comment]
Great =)

I guess i will start to work on it this weekend =)

**Comment by stephanrauh** [comment]
Looking at the [start page](https://github.com/stephanrauh/AngularFaces/blob/master/AngularFaces_2.0/AngularFaces.net/src/main/webapp/index.xhtml) of the tutorial, I think there's too much text to use the ```<translate>``` tag. Maybe it's better to translate a copy the page (for instance, index_pt.xhtml).

BTW, maybe it's easier to email each other. You reach me at webmaster1 arroba beyondjava.de.

**Comment by stephanrauh** [comment]
@bovino I've started to examine how to implement a version of ```<ui:include>``` that adds the language key to the file name. This would come in handy to translate the tutorial pages.

For some reason the implementations of Mojarra and MyFaces are very different from each other, so I'm not sure I'll succeed (because the new tag has to be compatible to both implementations).

**Comment by stephanrauh** [comment]
@bovino I've prepared the front page of AngularFaces.net to support multiple translations. All you have to do is to translate the [content_pt.xhtml](https://github.com/stephanrauh/AngularFaces/blob/master/AngularFaces_2.0/AngularFaces.net/src/main/webapp/content_pt.xhtml) file. Hope that makes your life easier.

![image](https://cloud.githubusercontent.com/assets/3045767/6653439/68b853d8-ca93-11e4-950a-81238b5a0de4.png)
