### ISSUE TITLE
Make versioning strategy consistent with angular.

### ISSUE THREAD

**Issue by ravshansbox** [stephanrauh/AngularFaces#40]
Make versioning strategy consistent with angular. Example: angularfaces 1.3.15 contains angular 1.3.15.

**Comment by stephanrauh** [comment]
That's a tad difficult since AngularFaces is already at version 2.1.4. But I'll keep the idea in the mind nonetheless. I expect AngularJS 1.4 to be released soon, so I could align AngularJS 1.4.x to AngularFaces 2.1.4.x.

**Comment by DimaSol** [comment]
Why should it be aligned with AngularJS and not JSF?!
I actually think that the right way is keep going with AngularFaces versioning as it is.
Why not creating some kind of compaitability matrix that will say for each version of AngularFaces what are the AngularJS & JSF compaitable versions?

**Comment by stephanrauh** [comment]
Currently, AngularFaces 2.1.x is compatible to AngularJS 1.3 and JSF 2.2+. In other words: it's aligned to neither of them :).

But you're right, a compatibility matrix might be a good idea.

BTW, currently I've decided to skip AngularJS 1.4. I'd rather use my spare time - as little as it is - supporting AngularJS 2.0. That'd be AngularFaces 2.2.0 :).
