### ISSUE TITLE
PropertyNotFoundException in ELTools

### ISSUE THREAD

**Issue by DimaSol** [stephanrauh/AngularFaces#42]
Hi,
When you invoking evalAsObject from inside ELTools itself you are not treating the PropertyNotFoundException that is thrown from AstValue.getTarget for example.
Such scenario is possible in case I don't really have a field behind a component when you are trying to get the field annotations for the NGBeanAttributeInfo.readJSR303Annotations

**Comment by stephanrauh** [comment]
OK - I'll fix that.

**Comment by stephanrauh** [comment]
AngularFaces was an interesting project, but it turned out to be impossible to migrate it to Angular 2, and since the, the Java community has abandoned UI programming altogether. So I'm closing all remaining tickets and archive the project.
