### ISSUE TITLE
ConservativeAngularTagDecorator results in "Configuration error"s

### ISSUE THREAD

**Issue by sixcorners** [stephanrauh/AngularFaces#61]
When I try to use the [ConservativeAngularTagDecorator](https://www.angularfaces.net/version2.1/tutorial/step_11/index.jsf) I get errors:
 
    16:23:21,141 SEVERE [de.beyondjava.angularFaces.core.transformation.PuiAngularTransformer] (default task-20) Add javax.faces.FACELETS_DECORATORS=de.beyondjava.angularFaces.core.tagTransformer.AngularTagDecorator to the context init parameters in the web.xml

I'm supposed to be using this instead of the AngularTagDecorator right? Not both at the same time?

**Comment by stephanrauh** [comment]
Sure, one of them is enough :). I simply forgot to add a test for the ConservativeAngularTagDecorator.

**Comment by stephanrauh** [comment]
Seems to be fixed - probably accidentially reopened.
