### ISSUE TITLE
Seems that readJSR303Annotations(component) is not working properly with DataTable inner components

### ISSUE THREAD

**Issue by DimaSol** [stephanrauh/AngularFaces#62]
Hi,
I'm getting PropertyNotFoundException when trying to read the value of a component inside a dataTable.
Seems that when trying to evaluate the value attribute of the component when the value is relative to the var attribute of the DataTable it is not working properly and return null when calling to vex.getValue(elContext) in ELTools.evalAsObject.
This is the stack trace:

AstValue.getTarget(EvaluationContext) line: 98	
AstValue.getValueReference(EvaluationContext) line: 355	
ValueExpressionImpl.getValueReference(ELContext) line: 277	
ELTools.evalAsObject(String) line: 93	
ELTools.getField(String) line: 266	
ELTools.readAnnotations(String) line: 411	
ELTools.readAnnotations(UIComponent) line: 432	
NGBeanAttributeInfo.readJSR303Annotations(UIComponent) line: 154	
NGBeanAttributeInfo.<init>(UIComponent) line: 63	
ELTools.getBeanAttributeInfos(UIComponent) line: 166	
AddTypeInformationCallback.visit(VisitContext, UIComponent) line: 35	
FullVisitContext.invokeVisitCallback(UIComponent, VisitCallback) line: 106	
HtmlSelectBooleanCheckbox(UIComponent).visitTree(VisitContext, VisitCallback) line: 1689	
Columns(UIComponent).visitTree(VisitContext, VisitCallback) line: 1700	
DataTable(OUIData).visitTree(VisitContext, VisitCallback) line: 1185	
DataTable(AbstractTable).visitTree(VisitContext, VisitCallback) line: 374

**Comment by stephanrauh** [comment]
Hi Dima, it's good to hear from you again! What do I have to do to reproduce your bug? Do you have a demo program I can simply download?

Thanks in advance
Stephan

**Comment by DimaSol** [comment]
It is reproducing when using in a data table the columns tag but unfortunately I wasn't able to reproduce it with PrimeFaces as wasn't able to use this tag as in the showcase (http://www.primefaces.org/showcase/ui/data/datatable/columns.xhtml). I'm currently using openfaces components and it is reproducing there with o:columns. I will keep trying to reproduce it with prime and update.

**Comment by DimaSol** [comment]
In the meanwhile it seems that the client side validation has other issues i.e. it is initializing jsf beans to try and find the jsr303 annotation of the bean members but while creating this beans they are not necessarily on the right state e.g. in my app invacation of ajax is (lazy) loading a panel and giving its bean an apropriate state (by implicitly calling some methods of it) but if this bean was created in the pre render view by the annotation scanner - it is on a wrong state what can cause an exception.

**Comment by DimaSol** [comment]
I think that I found somthing, one of the problems is that you are scanning components that are not yet rendered and this is why you force initialization of beans that shouldn't be initialized yet.
What I have found is that in PuiAngularTransformer.processEvent when you are creating the FullVisitContext at line 80 (root.visitTree) the hintsEnumSet is empty while I would expect it to have at least SKIP_UNRENDERED because on UIComponent.isVisitable the check fails if the component is not rendered but the hints has no SKIP_UNRENDERED.
What do you think?

**Comment by DimaSol** [comment]
Hi,
Did you had a chance to check regarding SKIP_UNRENDERED?

**Comment by stephanrauh** [comment]
I'm sorry, your ticket was pushed aside by my eagerness to finish the BootsFaces release. 

When I scanned the source code briefly, I didn't find SKIP_UNRENDERED. Is it a prefined constant of JSF?

However, I remembered something different. PrimeFaces reads annotations, too, but they used another approach that works fine with tables. I think I should examine this approach again and try to implement it in AngularFaces.

**Comment by stephanrauh** [comment]
While I couldn't reproduce your bug, I found several other bugs related to data tables. Plus, I examined and implemented your proposal regarding SKIP_UNRENDERED. It's a good idea, thanks!

Please try again with AngularFaces 2.1.9, which I've uploaded to Maven Central a couple of minutes ago.

```xml
<dependency>
  <groupId>de.beyondjava</groupId>
  <artifactId>angularFaces-core</artifactId>
  <version>2.1.9</version>
</dependency>
```

**Comment by DimaSol** [comment]
Hi,
Thank you for the reply and fix.
I hope to test it during next week and will update when done.

**Comment by DimaSol** [comment]
Hi,
It passed this phase so I guess your fix is working - thank you!
I'm now crashing on other stuff and still unvestigating the cause of it.
