### ISSUE TITLE
Convert Primefaces to Angulerfaces

### ISSUE THREAD

**Issue by Atul-Raut** [stephanrauh/AngularFaces#64]
Hi,
Please let me know, how to convert following code in AngularFaces.
```xml
<p:inputText value="#{cc.attrs[cc.attrs.fieldName]}"/>
```

And also let me know conversion in composite components.

**Comment by stephanrauh** [comment]
I'm afraid that's not possible :(. I'd have to investigate a lot to support composite components. But AngularFaces isn't used by many developers, so currently I prefer to invest this time in BootsFaces. When Angular2 get final, the situation may change again.
