### ISSUE TITLE
Page navigation alla SPA?

### ISSUE THREAD

**Issue by leolux** [stephanrauh/AngularFaces#65]
AngularJS implements the concept of a single page application (SPA) whereas JSF implements the concept of server side controlled applications. How do these two concepts fit together in AngularFaces? 

A more concrete questions: Is it possible to make use of angular's page navigation feature alla "../#/page/subpage" for each JSF page individually?

**Comment by leolux** [comment]
A good overview about this topic can be found here: http://www.beyondjava.net/blog/single-page-applications-with-bootsfaces/

**Comment by stephanrauh** [comment]
That's precisely the article I wanted you point you to :). Glad you liked it!
