### ISSUE TITLE
 I replaced the JSF syntax # {...} by an Angular-style syntax { {...}}.

### ISSUE THREAD

**Issue by leolux** [stephanrauh/AngularFaces#66]
>  I replaced the JSF syntax # {...} by an Angular-style syntax { {...}}.

When it is possible to use both JSF sysntax and angular syntax on the same xhtml page what do you mean by "replace"?

**Comment by leolux** [comment]
I took the quote from https://www.angularfaces.net/version2.1/tutorial/step_12/index.jsf

**Comment by stephanrauh** [comment]
Talking of it... well, maybe I should replace "replace" by a better word. Yes, you can use both syntaxes in an AngularFaces page. But the JSF syntax won't synchronize the beans with the AngularJS model. My original idea was to do just that: use the beans references by the JSF EL expressions, and synchronize them with the AngularJS model. But that didn't work for some technical reason. So I had to choose another syntax. My obvious choice was the AngularJS syntax. Originally, I didn't like that decision, but after a while I grew fond of it. First, the mustaches follow the Angular tradition, and second, developers now can chose whether they want to synchronize the JSF beans with the client or not.

That said: do you have a suggestion how to rephrase the sentence? I'm not a native speaker of English, so I appreciate your help!
