### ISSUE TITLE
angularfaces module not found

### ISSUE THREAD

**Issue by ratcashdev** [stephanrauh/AngularFaces#7]
Trying to use angularfaces, I stumbled on the following:
JConsole:
Uncaught Error: [$injector:modulerr] Failed to instantiate module MyApp due to:
Error: [$injector:modulerr] Failed to instantiate module angularfaces due to:
Error: [$injector:nomod] Module 'angularfaces' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.2.22/$injector/nomod?p0=angularfaces

I can see that the components.js is part of angularFaces-core-2.0.0.jar which I included via Maven. But how does this js get into the html page so that angular knows about it?

**Comment by Frecho12540** [comment]
Hi!
