### ISSUE TITLE
Link break in AngularFaces Website

### ISSUE THREAD

**Issue by subodhcjoshi82** [stephanrauh/AngularFaces#74]
I just trying to setp Angularfaces in my project so i went through this [link](https://angularfaces.net/version2.1/tutorial/step_01/index.jsf;jsessionid=BC13F49A7CB6CB30F1EE52E35A3E8D34) but when i tried example link its break Please find below is the link which is not working

> Example project on GitHub
> Check out the demo project at https://github.com/stephanrauh/AngularFaces/tree/master/Tutorial/step_01_labels_and_messages.

**Comment by subodhcjoshi82** [comment]
Another link break please go to this [link](https://www.angularfaces.net/version2.1/tutorial/step_00/index.jsf) here you can check 

> Requirements
> 
> You find the requirements in a [dedicated chapter](https://www.angularfaces.net/version2.1/version2.1/tutorial/step_99/requirements.jsf). Cutting a long story short: You need Java 6 and JSF 2.2.

This **dedicated chapter** link not working.

**Comment by stephanrauh** [comment]
The correct link to the tutorial probably is https://github.com/stephanrauh/AngularFaces/tree/master/AngularFaces.com/WebContent/tutorial/step_01.

The correct link to the "dedicated chapter" is https://www.angularfaces.net/version2.1/tutorial/step_99/requirements.jsf.

**Comment by stephanrauh** [comment]
Please note that I put AngularFaces on "hold". I'm told AngularFaces 2.1 is compatible with AngularJS 1.5, but I tested it only with AngularJS 1.3. Angular2 requires a new approach to AngularFaces, so don't expect your applications to work with Angular2.  

Currently, I don't work actively on AngularFaces, but if I resume work, I'll concentrate on the all-new Angular2 version.

**Comment by subodhcjoshi82** [comment]
Hi Stephen 

Thanks for your reply anyhow right now i am going with AngularJS1.x version only also AngularJs2 is not official launched as i know.So i will wait for your AngularJS2 Support with AngularFaces .Can you please tell us when you resume the work or when we can expect AngularFaces with AngularJS2 support?

Anyway i just started the coding in future will add more issue/question for you.Also please update the link in website.

**Comment by stephanrauh** [comment]
Currently, I don't have a timetable when or even if I resume work on an Angular2 version. The download figures of AngularFaces are very low, and the BootsFaces project takes most of my limited spare time.

**Comment by subodhcjoshi82** [comment]
Oh So we should use AngularFaces or not ? In future if you completely stop AngularFaces project its could be a big issue for the project which is using Angularfaces . So we have to confirm from you about this.

**Comment by stephanrauh** [comment]
The current version works, so there little risk using it. But I wouldn't bet on the future - unless you're ready to help me with the development.

**Comment by subodhcjoshi82** [comment]
Ha ha ha I like your above message . I already mentioned i am ready to help you.

**Comment by stephanrauh** [comment]
Oh, sorry, I should have looked before :).

**Comment by stephanrauh** [comment]
AngularFaces was an interesting project, but it turned out to be impossible to migrate it to Angular 2, and since the, the Java community has abandoned UI programming altogether. So I'm closing all remaining tickets and archive the project.
