### ISSUE TITLE
JavaScript Popup issue in angularfaces.net website.

### ISSUE THREAD

**Issue by subodhcjoshi82** [stephanrauh/AngularFaces#76]
I am trying to browse the following link [https://www.angularfaces.net/version2.0/index.html#/step-10.html](url) on page render its showing a popup with error written on this .

Please browse the link to get the error popup.
![errormessage](https://cloud.githubusercontent.com/assets/2179755/18262708/b2854f5a-7421-11e6-85f6-24cdb5e866e5.PNG)

**Comment by stephanrauh** [comment]
AngularFaces was an interesting project, but it turned out to be impossible to migrate it to Angular 2, and since the, the Java community has abandoned UI programming altogether. So I'm closing all remaining tickets and archive the project.
