### ISSUE TITLE
JSF converters

### ISSUE THREAD

**Issue by mjok** [stephanrauh/AngularFaces#80]
It seems that AngularFaces is incompatible with JSF  converters.

It works with #{..}, but not with {{..}}. Actually the converter is ivoked, but the value is still the same as beans field.
`

<h:outputLabel for="meanRadiusOfBellows"
	value="Mean Radius of bellows" />
<p:inputText id="meanRadiusOfBellows"
	value="#{calculateBellows.meanRadiusOfBellows}"
	converter="lt.mjok.btt.converters.MmToMeterConverter" />
<a style="margin-top: 0">mm</a>

<h:outputLabel for="radiusOfConvolutionRoot"
	value="Radius of convolution root" />
<p:inputText id="radiusOfConvolutionRoot" converter="lt.mjok.btt.converters.MmToMeterConverter"
	value="{{calculateBellows.radiusOfConvolutionRoot}}"
	 />
<a style="margin-top: 0">mm</a>`

**Comment by stephanrauh** [comment]
AngularFaces was an interesting project, but it turned out to be impossible to migrate it to Angular 2, and since the, the Java community has abandoned UI programming altogether. So I'm closing all remaining tickets and archive the project.
