### ISSUE TITLE
AngularFaces does not load the module

### ISSUE THREAD

**Issue by Frecho12540** [stephanrauh/AngularFaces#81]
Im new at AngularFaces and I've been trying to work with it the last two weeks. The error that I get is this one. 
![angulareeror](https://user-images.githubusercontent.com/11655761/28292299-aeb18ab0-6b0b-11e7-905c-62877ed7c206.PNG)

My loginController.js looks like this. 
![logincontroller](https://user-images.githubusercontent.com/11655761/28292374-eaf15410-6b0b-11e7-8691-c3cbcfac3426.PNG)

Do I have to add a extra script to my xhtml file? I already have all the jars that AngularFaces needs according to this [https://angularfaces.com/index.html#/step-00.html](url)
![librerias](https://user-images.githubusercontent.com/11655761/28292450-42173c96-6b0c-11e7-9c63-26e4681f9949.PNG)

Hope anyone can help me.

**Comment by stephanrauh** [comment]
AngularFaces was an interesting project, but it turned out to be impossible to migrate it to Angular 2, and since the, the Java community has abandoned UI programming altogether. So I'm closing all remaining tickets and archive the project.
